name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Create serviceAccountKey.json file from the base64-encoded secret
      - name: Create serviceAccountKey.json file
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}" | base64 -d > serviceAccountKey.json

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn run
          start: yarn cypress:run
          wait-on-timeout: 120
          browser: chrome
